#!/bin/bash
# I hate bash documentation

set -e

function joinBy {
    local sep="$1"
    shift

    printf "$sep '%s' " "${@}" # use with care
}

function runUnlessAlreadyRunning {
    local run="$1"
    shift
    local greps
    greps=$(joinBy '| grep' "${@}")
    local result
    result=$(eval "ps ax | grep -v grep $greps || true")

    if [ -z "$result" ]
    then
        eval "$run"
    fi
}

function startXmonad {
    xmonad --replace &
    sleep 2
    xrandr --output eDP-1 --brightness 0.5
    wins=$(wmctrl -l | awk '{print $1}')
    for window in $wins; do
        wmctrl -i -r "$window" -t 9
    done
    emacs &
    gnome-terminal -- /bin/sh -c "ssh-add; zsh -c \"tmux; zsh -i\""
    feh --bg-scale --randomize /usr/share/backgrounds/
}

setxkbmap -option ctrl:swapcaps

runUnlessAlreadyRunning "eval \"$(ssh-agent -s)\"" ssh-agent

runUnlessAlreadyRunning startXmonad xmonad replace

#xrandr --output eDP-1 --scale 0.5x0.5
