#!/bin/bash

from=2
to=852
brightnessFile=/sys/class/backlight/intel_backlight/brightness

toPercentage() {
    local brighnessLevel="$1"

    echo "scale=4; ($brighnessLevel - $from) / ( $to - $from ) * 100" | bc
}

toBrightnessLevel() {
    local percentage="$1"

    # brighness goes from, to
    echo "scale=4; res = $percentage / 100.0 * ( $to - $from ) + $from; scale=0; res/1" | bc
}

readBrightness() {
    toPercentage "$(cat $brightnessFile)"
}

updateBrighness() {
    toBrightnessLevel "$1" | sudo tee $brightnessFile
}

if [ $# -eq 0 ]
then
    readBrightness
else
    updateBrighness "$1"
fi
